[package]
name = "term"
version = "0.0.0"

edition = "2018"
resolver = "2"

[dependencies]
libc = "0.2"
phf = { version = "0.10", features = ["macros"] }
phf_shared = "0.10"
tinyvec = { version = "1.3", features = ["alloc"] }
